# # version: 0.2
# # env:
# #     variables:
# #         CACHE_CONTROL: "86400"
# #         S3_BUCKET: "arn:aws:s3:::suraj1998bucket"
# #         BUILD_FOLDER: "dist"
# # phases:
# #   install:
# #     runtime-versions:
# #         nodejs: 16
# #     commands:
# #         - echo Installing source NPM dependencies...
# #         - npm install
# #         - npm install -g @angular/cli
# #   build:
# #     commands:
# #         - echo Build started 
# #         - ng build
    
   
# # artifacts:
# #     files:
# #         - '**/*'
# #     base-directory: 'dist'
# #     discard-paths: yes

# version: 0.2
# env:
#     variables:
#         CACHE_CONTROL: "86400"
#         S3_BUCKET: "arn:aws:s3:::suraj1998bucket"
#         BUILD_FOLDER: "dist"
# phases:
#   install:
#     runtime-versions:
#         nodejs: 16
#     commands:
#         - echo Installing source NPM dependencies...
#         - npm install
#         - npm install -g @angular/cli
#   build:
#     commands:
#         - echo Build started 
#         - npm run build:ssr
#   post_build:
#     commands:
#         - aws s3 cp s3://suraj1998bucket/Procfile .
#         - aws s3 cp s3://suraj1998bucket/.npmrc .
#         - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
 
# artifacts:
#     files:
#         - '**/*'
#     base-directory: 'dist'